pr2_l_site_accueil:
    path:     /pr2l/accueil
    defaults: { _controller: PR2LSiteBundle:Default:accueil }

pr2_l_site_actionsEvenements:
    path:     /pr2l/actionsEvenements
    defaults: { _controller: PR2LSiteBundle:Default:actionsEvenements }
    
pr2_l_site_projet:
    path:     /pr2l/projet
    defaults: { _controller: PR2LSiteBundle:Default:projet }
    
pr2_l_site_fondateurs:
    path:     /pr2l/fondateurs
    defaults: { _controller: PR2LSiteBundle:Default:fondateurs }
    
pr2_l_site_revuePresse:
    path:     /pr2l/revuePresse
    defaults: { _controller: PR2LSiteBundle:Default:revuePresse }
    
pr2_l_site_adherer:
    path:     /pr2l/adherer
    defaults: { _controller: PR2LSiteBundle:Default:adherer }
    
pr2_l_site_vieAssociation:
    path:     /pr2l/vieAssociation
    defaults: { _controller: PR2LSiteBundle:Default:vieAssociation }
    
pr2_l_site_actualites:
    path:     /pr2l/actualites
    defaults: { _controller: PR2LSiteBundle:Default:actualites }
    
pr2_l_site_quoiDeNeuf:
    path:     /pr2l/quoiDeNeuf
    defaults: { _controller: PR2LSiteBundle:Default:quoiDeNeuf }
    
pr2_l_site_autourDeNous:
    path:     /pr2l/autourDeNous
    defaults: { _controller: PR2LSiteBundle:Default:autourDeNous }
    
pr2_l_site_partenaires:
    path:     /pr2l/partenaires
    defaults: { _controller: PR2LSiteBundle:Default:partenaires }
    
pr2_l_site_gererPartenaires:
    path:     /pr2l/gererPartenaires
    defaults: { _controller: PR2LSiteBundle:Default:gererPartenaires }
    
pr2_l_site_ressources:
    path:     /pr2l/ressources
    defaults: { _controller: PR2LSiteBundle:Default:ressources }
    
pr2_l_site_archives:
    path:     /pr2l/archives
    defaults: { _controller: PR2LSiteBundle:Default:archives }
    
pr2_l_site_bibliotheque:
    path:     /pr2l/bibliotheque
    defaults: { _controller: PR2LSiteBundle:Default:bibliotheque }
    
pr2_l_site_travauxRecherche:
    path:     /pr2l/travauxRecherche
    defaults: { _controller: PR2LSiteBundle:Default:travauxRecherche }
    
pr2_l_site_publications:
    path:     /pr2l/publications
    defaults: { _controller: PR2LSiteBundle:Default:publications } 
        
pr2_l_site_liensUtiles:
    path:     /pr2l/liensUtiles
    defaults: { _controller: PR2LSiteBundle:Default:liensUtiles }     
    
pr2_l_site_chantiers:
    path:     /pr2l/chantiers
    defaults: { _controller: PR2LSiteBundle:Default:chantiers }  
    
pr2_l_site_recensementMutualite:
    path:     /pr2l/recensementMutualite
    defaults: { _controller: PR2LSiteBundle:Default:recensementMutualite }  
    
pr2_l_site_intranet:
    path:     /pr2l/intranet
    defaults: { _controller: PR2LSiteBundle:Default:intranet }  
    
pr2_l_site_connexion:
    path:     /pr2l/connexion
    defaults: { _controller: PR2LSiteBundle:Default:connexion }
    
pr2_l_site_creation:
    path:     /pr2l/creation
    defaults: { _controller: PR2LSiteBundle:Default:creation }
    
pr2_l_site_gestionAdmin:
    path:     /pr2l/gestionAdmin
    defaults: { _controller: PR2LSiteBundle:Default:gestionAdmin }
    
pr2_l_site_modification:
    path:     /pr2l/modification
    defaults: { _controller: PR2LSiteBundle:Default:modification }
    
pr2_l_site_deconnexion:
    path:     /pr2l/deconnexion
    defaults: { _controller: PR2LSiteBundle:Default:deconnexion }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    